export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS'
export const FETCH_ALL_RECIPES_REQUEST = 'FETCH_ALL_RECIPES_REQUEST'
export const FETCH_ALL_RECIPES_ERROR = 'FETCH_ALL_RECIPES_ERROR'

export const FETCH_RECIPE_REQUEST = 'FETCH_RECIPE_REQUEST'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR'

export const CREATE_RECIPE_REQUEST = 'CREATE_RECIPE_REQUEST'
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS'
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR'

export const UPDATE_RECIPE_REQUEST = 'UPDATE_RECIPE_REQUEST'
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS'
export const UPDATE_RECIPE_ERROR = 'UPDATE_RECIPE_ERROR'

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST'
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS'
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR'

export const CHANGE_RECIPE_RATING_REQUEST = 'CHANGE_RECIPE_RATING_REQUEST'
export const CHANGE_RECIPE_RATING_SUCCESS = 'CHANGE_RECIPE_RATING_SUCCESS'
export const CHANGE_RECIPE_RATING_ERROR = 'CHANGE_RECIPE_RATING_ERROR'

// Не уверен, может это ответственность компонента, а не редакса?
export const TOGGLE_SORT_BY_RATING_FLAG = 'TOGGLE_SORT_BY_RATING_FLAG'
export const CHANGLE_RECIPE_TITLE_FILTER = 'CHANGLE_RECIPE_TITLE_FILTER'